Fixed an operator precedence issue in the math_number_property generators to remove extra parentheses
google/blockly pull request #5685
Opened 2021-11-06 02:42 UTC by RichDoherty

## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

## The details
### Partially Resolves

https://github.com/google/blockly/issues/4353 

### Proposed Changes

Fixes an issue in the math_number_property generator. Changed the order of the outerOrder argument to valueToCode to reflect that there are "is prime," "is positive," and "is negative" options. Corrected the return value order for "is positive" and "is negative" in JavaScript, PHP, and Dart.

#### Behavior Before Change

Extra parentheses were added when arithmetic blocks were placed in "is prime," "is positive," and "is negative" math_number_property blocks (excluding exponentiation) because ORDER_MODULUS/ORDER_MULTIPLICATIVE was being used instead of ORDER_NONE/ORDER_RELATIONAL. Extra parentheses were also added if you put "is positive" or "is negative" into a logic compare block because ORDER_EQUALITY was being used instead of ORDER_RELATIONAL. 

#### Behavior After Change

No extra parentheses are added.

### Reason for Changes

To remove unneeded parentheses in generated code.

### Test Coverage

Tested locally.

Tested on: 
* Desktop Chrome
* Desktop Firefox

### Documentation

None necessary.

### Additional Information

Still working right now on fixes for Python, Lua, PHP, and Dart.

2021-11-06 03:34 UTC, RichDoherty commented
@googlebot I signed it!

2021-11-07 23:49 UTC, jeremyjacob123 commented
@googlebot I signed it!

2021-11-08 04:16 UTC, jschanker commented
@NeilFraser RE: the discussion from #5678, would we want to change the generated code for PHP (and update the tests) so that it uses `===` instead of `==` when code execution would remain unchanged as well?

2021-11-08 07:17 UTC, jschanker commented on generators/lua/math.js
> +
This code from the previous version should have been removed.

2021-11-08 07:17 UTC, jschanker commented on generators/dart/math.js
> +        const functionName = Blockly.Dart.provideFunction_(
This should only be indented four spaces.

2021-11-09 02:16 UTC, LouisCatala commented
@googlebot I fixed it

2021-11-09 02:27 UTC, LouisCatala commented
@googlebot I signed it!

2021-11-18 17:11 UTC, cpcallen requested changes
Hi @RichDoherty,

This looks great.  There's just one small improvement I have to suggest (to be applied in several places); see below.

The main thing we'd like to see before merging this pull request added generator tests for the new code paths.  I suggest you add them on a separate branch (branched from `develop`), make sure they fail there, then cherry-pick them onto this branch (and make sure they pass here, obviously).

2021-11-20 05:59 UTC, jeremyjacob123 commented on generators/lua/math.js
> -      // because nil is false, so allow a runtime failure. :-(
I'm a little confused by this comment. number_to_check % 0 doesn't cause a division by 0 runtime failure in Lua. This doesn't seem as if it is an issue with Blockly itself?

2021-11-21 04:54 UTC, RichDoherty commented
@cpcallen 

>This looks great. There's just one small improvement I have to suggest (to be applied in several places); see below.

Thank you for taking the time to review our pull request. 

>The main thing we'd like to see before merging this pull request added generator tests for the new code paths.

We added some block tests to account for extra parentheses and a test for the remainder when dividing by 0, but we weren't sure what to do with the Lua comment.
[https://github.com/google/blockly/pull/5685#discussion_r753639058](https://github.com/google/blockly/pull/5685#discussion_r753639058)

2021-12-11 00:11 UTC, cpcallen commented on generators/lua/math.js
> -      // because nil is false, so allow a runtime failure. :-(
I don't know much Lua but a cursory check of running `print(1%0)` using [the online Lua demo](https://www.lua.org/cgi-bin/demo) gives a runtime error of `input:1: attempt to perform 'n%0'`, so AFAICT the originally-documented issue still exists, and so the documentation about it should be preserved.

2021-12-11 00:24 UTC, cpcallen requested changes
Thanks for adding tests.  They look good (but see some minor nit-picking about the XML input, below).

I see there are conflicts.  This is doubtless because we touched a lot of code in the generators last week, converting them from `goog.provide` to `goog.module`, so you'll need to merge `develop` into this branch (or rebase it on top of the current tip of `develop`).  Sorry to make more work for you!

2021-12-11 00:24 UTC, cpcallen commented on tests/generators/math.xml
> +        <field name="VAR" id="vC|N=?5}X^+}FPTXGW`X">varToChange</field>
Please remove unneeded variable `id`s.

2021-12-11 00:24 UTC, cpcallen commented on tests/generators/math.xml
> +    <comment pinned="false" h="80" w="160">Describe this function...</comment>
It would be preferable also to revert meaningless changes like these.

2021-12-11 05:04 UTC, RichDoherty commented on generators/lua/math.js
> -      // because nil is false, so allow a runtime failure. :-(
We added the comment back in, but when running `print(1%0)` on [https://repl.it/languages/lua](https://repl.it/languages/lua) the output is `-nan`. Although not official documentation, [https://rosettacode.org/wiki/Detect_division_by_zero#Lua](https://rosettacode.org/wiki/Detect_division_by_zero#Lua) seems to suggest that this is expected?

2021-12-11 05:08 UTC, RichDoherty commented
Made the suggested changes, but still not sure about the discrepancies for Lua.

2022-01-25 16:42 UTC, cpcallen commented
> Made the suggested changes, but still not sure about the discrepancies for Lua.

Please restore the comment that was on lines 186–188.

It looks like the Lua generator produces code that is very slightly buggy.  We should fix that, but it doesn't need to be fixed in this PR.  We do want to keep the comment pointing out the problem, though!

2022-01-25 23:44 UTC, jeremyjacob123 commented
> Please restore the comment that was on lines 186–188.
>
> It looks like the Lua generator produces code that is very slightly buggy. We should fix that, but it doesn't need to be fixed in this PR. We do want to keep the comment pointing out the problem, though!

The comment from lines 186-188 was placed [here.](https://github.com/google/blockly/pull/5685/files#diff-024099ec49a554c64ca542911c66dbafcb76624414577ac1498e33a8f95e76b2R181-R183) Thanks!

2022-01-27 15:50 UTC, cpcallen commented
> > Please restore the comment that was on lines 186–188.
> > It looks like the Lua generator produces code that is very slightly buggy. We should fix that, but it doesn't need to be fixed in this PR. We do want to keep the comment pointing out the problem, though!
> 
> The comment from lines 186-188 was placed [here.](https://github.com/google/blockly/pull/5685/files#diff-024099ec49a554c64ca542911c66dbafcb76624414577ac1498e33a8f95e76b2R181-R183) Thanks!

Oh… somehow I overlooked that.  Mea culpa.  I apologise for wasting your time asking you to do something that you had already done!

2022-01-27 15:54 UTC, merged