refactor(blocks): Migrate `blocks/loops.js` to TypeScript
google/blockly pull request #6957
Opened 2023-04-07 00:02 UTC by rachel-fenichel

## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [x] I ran `npm run format` and `npm run lint`

## The details
### Resolves

Part of #6828 

### Proposed Changes

Migrates loop blocks, following the examples in #6900 and #6901

2023-04-17 15:06 UTC, cpcallen requested changes
LGTM except for a few @directives that should be removed.  A few additional comments with queries for my curiosity.

2023-04-17 15:06 UTC, cpcallen commented on blocks/loops.ts
>   * @mixin
See above.

2023-04-17 15:06 UTC, cpcallen commented on blocks/loops.ts
> +    const enabled = !!this.getSurroundLoop();
Good for clarity!  I'm curious: was this necessary to get the ternary below to type-check?

2023-04-18 16:23 UTC, rachel-fenichel commented on blocks/loops.ts
> +import type {Abstract} from '../core/events/events_abstract.js';
Done

2023-04-18 22:58 UTC, merged