fix: circle animation persistence
google/blockly pull request #7242
Opened 2023-07-01 19:02 UTC by Plomging

## The basics

- [ x] I branched from develop
- [x ] My pull request is against develop
- [ x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [ x] I ran `npm run format` and `npm run lint`

## The details
### Resolves

Fixes https://github.com/google/blockly/issues/7241

### Proposed Changes

Switch animation method : Use the "animate" element and remove the "circle" element after 150ms (duration of the animation)

#### Behavior Before Change

See issue

#### Behavior After Change

No more circles

### Reason for Changes

When there are many circles, the interface becomes unusable

### Test Coverage

N/A

### Documentation

No

### Additional Information

No

2023-07-14 00:12 UTC, maribethb commented
Hello, thank you for the PR! Sorry for the delay in review, but I need to learn some stuff about animating SVGs before I can adequately respond, and I haven't had the time this week, but it is on my todo list.

2023-07-26 20:57 UTC, BeksOmega requested changes
Generally LGTM! Thank you for the fixes :D Just two small changes then should be gtg!

2023-07-26 20:57 UTC, BeksOmega commented on core/block_animations.ts
> +      'begin': 'animationCircle.begin',
I don't think this is actually triggering the opacity animation :/ Could you kick it off manually with `beginElement` like how you're triggering the other one?

2023-07-26 20:57 UTC, BeksOmega commented on core/block_animations.ts
> +    },
```suggestion
    () => void dom.removeNode(ripple);,
```

This is not actually a functional change, just a style thing :P

2023-07-31 15:46 UTC, BeksOmega commented
Heya @Plomging Just giving you a heads up I'm planning to close this as stale on Friday if this hasn't had a response =) Just leave a comment if you're still working on this!

2023-08-08 22:43 UTC, BeksOmega commented
Closing as stale.

2023-08-08 22:43 UTC, closed without merging