chore: create test for mutator
google/blockly pull request #7278
Opened 2023-07-11 18:31 UTC by ericblackmonGoogle

## The basics

- [x] I branched from develop
- [x] My pull request is against develop
- [x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
- [x] I ran `npm run format` and `npm run lint`

## The details

### Proposed Changes

Creates a functional test for the Blockly mutator  function. As the test is more reliant on the mutator rather than the regular flyout and workspace it has a greater reliance on css selectors (there are no helper methods currently for it).

2023-07-14 00:08 UTC, maribethb commented on tests/browser/test/mutator_test.js
> +  const ifDoTransformCountBefore = (ifDoNumHTML.match(/transform/g) || [])
I wonder if there is a better thing to assert on than this? it's pretty abstract. it wouldn't be obvious to me if this failed what should have happened or what is broken. I think a better test would be to use the Blockly APIs to check that the block has more inputs now (if you add an else block in the mutator then the final block should have another statement input)

2023-07-14 00:08 UTC, maribethb commented on tests/browser/test/mutator_test.js
> +  console.log(ifDoTransformCountBefore);
Please remove console logs to keep test console easy to read

2023-07-14 00:08 UTC, maribethb commented on tests/browser/test/mutator_test.js
> +  await new Promise((resolve) => setTimeout(resolve, 2000)); // 2 sec
You can use `browser.pause(200)` to wait instead. You hopefully shouldn't have to wait for 2 entire seconds either so consider making this shorter, or using `waitForExist` on the `elseIf` element below.

2023-07-14 00:08 UTC, maribethb commented on tests/browser/test/mutator_test.js
> +  elseIfFlyout.dragAndDrop({x: delta * 50, y: 42});
Can you use the new helper methods to connect blocks instead? They do some math to find the correct place for the drag and that's what allows the tests to pass on linux as well as mac.

2023-07-26 23:11 UTC, rachel-fenichel requested changes

2023-07-26 23:11 UTC, rachel-fenichel commented on tests/browser/test/test_setup.js
> + * @param mutatorBlockId The block that holds the mutator icon
Add "or null if the target block is on the main workspace"

2023-07-26 23:11 UTC, rachel-fenichel commented on tests/browser/test/mutator_test.js
> +  suiteTeardown(async function () {
My recent changes mean you no longer need to do teardown.

2023-07-26 23:11 UTC, rachel-fenichel commented on tests/browser/test/mutator_test.js
> +  // Get the ids for block before mutating
This comment should be "Get the original number of mutator inputs."

2023-07-26 23:11 UTC, rachel-fenichel commented on tests/browser/test/mutator_test.js
> +  // Get the original number of mutator inputs
Remove this comment.

2023-07-26 23:11 UTC, rachel-fenichel commented on tests/browser/test/mutator_test.js
> +    browser = await testSetup(testFileLocations.PLAYGROUND);
Use `this.browser = await testSetup(testFileLocations.PLAYGROUND)` here, then pass `this.browser` as an argument to `testingMutator` below:

`await testingMutator(this.browser, screenDirection.LTR);`

and define `testingMutator` to take a `browser` parameter:

`async function testingMutator(browser, delta)`

Then delete the declaration of `browser` on line 22.

The combination of all of these changes means that there is no longer a global `browser` object, which protects you from accidentally sharing state between tests.

2023-07-26 23:11 UTC, rachel-fenichel commented on tests/browser/test/mutator_test.js
> +  chai.assert.isTrue(afterInputs > originalInputs);
Assert that it's equal to a specific number of inputs at the end, rather than asserting that it's greater than the original number.

2023-07-26 23:11 UTC, rachel-fenichel commented on tests/browser/test/test_setup.js
> + * @param mutatorBlockId The block that holds the mutator icon
Add "or null if the target block is on the main workspace"

2023-07-26 23:11 UTC, rachel-fenichel commented on tests/browser/test/test_setup.js
> + * @param dragBlockSelector The selector of the block to drag
Add "or null if the target block is on the main workspace"

2023-07-27 15:34 UTC, merged