Addition of the .gitattributes file to standardize line endings
google/blockly pull request #7517
Opened 2023-09-22 18:21 UTC by sam301100

Description:

Issue: [#7191](https://github.com/google/blockly/issues/7191)

Overview:

This pull request addresses the issue reported in [#7191](https://github.com/google/blockly/issues/7191) by adding a .gitattributes file to standardize line endings within the Blockly project.

Changes:

Added a .gitattributes file with the following configuration to ensure consistent line endings:
* text eol=lf

Motivation:

Standardizing line endings to LF (Unix-style) is essential for maintaining code consistency across different platforms and prevents issues related to mixed line endings when collaborating on projects.

Testing:

I have tested these changes locally by cloning the repository and verifying that the .gitattributes file is properly applied to the project. Line endings are consistent with LF, as expected.

...
Thank you for considering this pull request. I'm excited to contribute to the Blockly project during the Grace Hopper Celebration 2023 Open Source Day. Please let me know if there are any additional changes or improvements needed for this contribution.

2023-09-22 20:18 UTC, maribethb requested changes
Hi @sam301100 Thank you for opening this PR! It needs just a few changes before it can be merged:
- All contributors need to sign the CLA; you can follow googlebot's instructions in the comment it left to sign the CLA and refresh the check
- Update your PR title to start with `fix: ` so that our tools can properly categorize this PR as a fix
- Address the comment left in the PR review

After you take care of these few things we'll be able to merge your PR! Thank you!

2023-09-22 20:18 UTC, maribethb commented on .gitattributes
> +* text eol=lf
The contents of this file should be: `* text=auto`

This allows folks to use whatever line endings are configured on their OS, but when they get checked into git they'll be standardized to lf. Let me know if that doesn't seem to be working for you!

2023-09-22 22:55 UTC, sam301100 commented
Hi @maribethb,
I have made the changes. Requesting you to approve the merge.

Thank you,
Samruddhi Somwanshi

2023-09-23 16:30 UTC, maribethb approved these changes
Looks good! Thank you for your contribution!

2023-09-23 16:30 UTC, merged