(feat): added Set to prevent console logging multiple deprecation warning #7719
google/blockly pull request #7733
Opened 2023-12-20 00:05 UTC by ebrahim95

## The basics

- [ X] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

## The details
### Resolves

Fixes https://github.com/google/blockly/issues/7719

### Proposed Changes

I added the Set Data structure to the deprecation.ts file to prevent logging multiple deprecation warnings.

### Reason for Changes

The changes need to be made because if there are multiple warnings that have the same message,
then the warnings will be logged more than once in the console.

### Test Coverage

I tested this by adding:
`Blockly.utils.deprecation.warn('test warning', 'vA', 'vB', 'test substitute');
Blockly.utils.deprecation.warn('test warning', 'vA', 'vB', 'test substitute');`
to the playground.html file. 
If the warning appears once then the test was successful.

### Documentation

### Additional Information

2023-12-21 17:10 UTC, cpcallen requested changes
Hi ebrahim95, and thanks for this contribution!

Overall it looks great but there is one small thing that needs to be fixed to comply with our style guide, and one other suggestion I have to make the code easier to read.

(I've also taken the liberty of tweaking some of your comments and the PR title to better fit with our usual style.)

2023-12-21 19:52 UTC, ebrahim95 commented
@cpcallen I appreciate the suggestions :smile: 
They have helped me understand how to write readable code.

2024-01-05 17:25 UTC, cpcallen approved these changes

2024-01-05 17:27 UTC, cpcallen requested changes
Looks like you didn't update the other places that `checkMsg` is used, and now there are syntax errors.

2024-01-09 21:15 UTC, cpcallen approved these changes

2024-01-09 21:20 UTC, merged