chore!: Rename editing CSS class to blocklyEditing (#8287)
google/blockly pull request #8301
Opened 2024-07-11 00:48 UTC by ga-fleury

- **chore!: Rename editing CSS class to blocklyEditing (#8287)**

2024-07-11 16:43 UTC, BeksOmega commented
Yay! Glad it looks like you got the branches sorted :D

Two housekeeping things that apply to all of your PRs:
1. Commenting on issues is important. Even if I don't assign it to you before you complete it, it lets other folks know it is being worked on, so they can look at other issues.
2. Filling out the PR template is important. At the bare minimum you need the `Fixes: #issue` line, because there is GitHub automation associated with that. I'll fix your existing PRs, but for any future PRs you'll have to do this.

Please reply or react to let me know you've seen this!

2024-07-11 16:48 UTC, ga-fleury commented
> Yay! Glad it looks like you got the branches sorted :D
> 
> Two housekeeping things that apply to all of your PRs:
> 
> 1. Commenting on issues is important. Even if I don't assign it to you before you complete it, it lets other folks know it is being worked on, so they can look at other issues.
> 2. Filling out the PR template is important. At the bare minimum you need the `Fixes: #issue` line, because there is GitHub automation associated with that. I'll fix your existing PRs, but for any future PRs you'll have to do this.
> 
> Please reply or react to let me know you've seen this!

Will do! thank you for the heads up!

2024-07-11 16:59 UTC, BeksOmega requested changes
Missed this in the issue description, but there is also a places in `core/field_input` where we call `dom.removeClass` with `editing`. This needs to be renamed as well.

After that should be gtg!

2024-07-17 16:55 UTC, BeksOmega commented
Heya @ga-fleury Are you still interested in working on this?

2024-07-17 17:18 UTC, ga-fleury commented
@BeksOmega added further changes

2024-07-22 22:38 UTC, BeksOmega approved these changes
This looks great! Thank you for the fixes =)

2024-07-22 22:38 UTC, merged