fix!: #8345 rename css class
google/blockly pull request #8357
Opened 2024-07-14 02:25 UTC by Abhinav-Chdhary

## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

## The details
- This commit renames the blocklyTreeRow CSS class to blocklyToolboxCategory.
- The commit was made against v12.0.0 branch
- It is a breaking change

### Fixes #8345

2024-07-15 20:10 UTC, BeksOmega requested changes
Thanks for digging into this! Just a few fixes then should be gtg.

2024-07-15 20:10 UTC, BeksOmega commented on core/toolbox/category.ts
There are some other references `blocklyTreeRow` in this file. Could you rename them as well?

2024-07-16 01:39 UTC, Abhinav-Chdhary commented on core/toolbox/category.ts
Yes, let me know if this change works.

2024-07-16 15:40 UTC, BeksOmega requested changes
Thanks for the fixes! But now it looks like some Mocha tests are failing. Could you look into what's going wrong? You can run them locally by doing `npm run test:mocha:interactive`.

2024-07-16 16:55 UTC, BeksOmega requested changes
Ah I see the issue, this is my bad. We've created a conflict between the CSS class of the container and the CSS class of the row. Could you name the original uses of `blocklyToolboxCategory` to `blocklyToolboxCategoryContainer` as well? I think that should fix the problem!

2024-07-16 17:14 UTC, Abhinav-Chdhary commented
> Ah I see the issue, this is my bad. We've created a conflict between the CSS class of the container and the CSS class of the row. Could you name the original uses of `blocklyToolboxCategory` to `blocklyToolboxCategoryContainer` as well? I think that should fix the problem!

I have tried to do so. It passes all tests locally.

2024-07-16 17:59 UTC, BeksOmega approved these changes
Sweetness! Thank you for the back and forth, this looks beautiful =)

2024-07-16 18:00 UTC, merged