Skye dev
google/blockly pull request #8360
Opened 2024-07-14 22:13 UTC by Skye967

… style to :focus

## The basics

- [x ] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

## The details
### Resolves

Fixes 

[https://github.com/google/blockly/issues/8326](url)

### Proposed Changes

Remove the blocklyFocused class from being assigned in menu.ts and dropdowndiv.ts
Change the styles in css.ts to use the :focus css pseudo class

Removed the blocklyFocused class from being assigned in menu.ts and dropdowndiv.ts
Changed the styles in css.ts to use the :focus css pseudo class

### Reason for Changes

### Test Coverage

Not necessary 

### Documentation

No it won't affect anything. just some minor css changes

### Additional Information

2024-07-14 22:27 UTC, Skye967 commented
Sorry about that, getting used to the naming conventions and I submitted the CLA. Other than that, do the changes look good?

2024-07-15 20:19 UTC, BeksOmega commented
Hello! Thanks for the fix and for signing the CLA :D

It looks like your branch has a few extra commits. To remove the commits that aren't yours, you can rebase your branch on top of the latest `rc/v12.0.0` branch.  This will remove any commits that were added to `rc/v12.0.0` since you created your branch.

Here are the steps to do that:

1. **Fetch the latest changes from `rc/v12.0.0`:**

   ```bash
   git fetch upstream rc/v12.0.0
   ```

2. **Checkout your branch:**

   ```bash
   git checkout [your-branch-name]
   ```

3. **Start an interactive rebase:**

   ```bash
   git rebase -i upstream/rc/v12.0.0
   ```

4. **In the editor that opens, identify the commits that aren't yours.** These are likely the ones at the top of the list. 

5. **Change the word `pick` to `drop` for each commit you want to remove.** 

6. **Save and close the editor.**

8. **Force push your changes to your branch:** Note that force pushing is a dangerous operation because it overwrites commit history, so if you dropped the wrong commits you could lose work.

   ```bash
   git push -f origin [your-branch-name]
   ```

Once you've done this, the PR should only contain your commits.

Let me know if you have any questions or run into any issues!

2024-07-15 20:20 UTC, BeksOmega requested changes
Marking this as changes requested.

2024-07-22 22:51 UTC, BeksOmega requested changes
One comment, but changes to the dropdown div look good!

2024-07-22 22:51 UTC, BeksOmega commented on core/css.ts
> -.blocklyDropDownDiv.blocklyFocused {
There is another reference to `.blocklyFocused` in this file, could you remove it as well?

2024-07-24 19:38 UTC, Skye967 commented
Went of core css and made some changes.

2024-07-25 01:06 UTC, BeksOmega approved these changes
Sweet LGTM =) I'll get this merged once CI passes

2024-07-25 01:09 UTC, BeksOmega requested changes
Can you fix the lint errors?

2024-07-26 13:47 UTC, Skye967 commented
I believe everything is good now.

2024-07-27 01:16 UTC, BeksOmega approved these changes

2024-07-27 01:16 UTC, BeksOmega commented
Thanks for your hard work on this!

2024-07-27 01:16 UTC, merged