Remove redundant blocklyNonSelectable class and integrate non-selectability into existing classes
google/blockly pull request #8387
Opened 2024-07-17 17:33 UTC by dakshkanaujia

…bility into existing classes
#8328 

## The basics

- [ ] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

## The details
### Resolves

Fixes 

### Proposed Changes

### Reason for Changes

### Test Coverage

### Documentation

### Additional Information

This PR addresses issue #8328 by removing the redundant blocklyNonSelectable CSS class. The non-selectability functionality previously provided by this class has been integrated into the existing classes where it is applied. This simplifies the code and ensures non-selectability is maintained without the need for an additional class.

Added the functionality in classes :-
##blocklyMenu
##blocklyToolboxDiv

2024-07-22 22:18 UTC, BeksOmega requested changes
Hello @dakshkanaujia It looks like you made some extra changes (to a .gitpod file and a blocklyMenu.code-search file) Could you remove those?

2024-07-25 01:18 UTC, BeksOmega reviewed
One question, then I'll let CI run and get this merged =)

2024-07-25 01:18 UTC, BeksOmega commented on core/toolbox/toolbox.ts
> +    // dom.addClass(toolboxContainer, 'blocklyNonSelectable');
Can you remove this instead of commenting it out?

2024-07-25 01:18 UTC, BeksOmega commented on core/toolbox/separator.ts
> +  user-select: none;
I understand where all of the other changes came from, but why is this here?

2024-07-25 10:19 UTC, dakshkanaujia commented
Hey @BeksOmega , Thank you for pointing that out =), I have done the required changes in the latest PR, please review it !

2024-07-26 09:25 UTC, dakshkanaujia commented
Hopefully! now the checks will pass

2024-07-27 01:20 UTC, BeksOmega commented
Ah sorry, it looks like my comment didn't post.

This needs to be against the `rc/v12.0.0` instead of develop. To rebase onto the rc/v12.0.0 branch, you can follow these steps.


1. **Fetch the latest changes from `rc/v12.0.0`:**

   ```bash
   git fetch upstream rc/v12.0.0
   ```

2. **Checkout your branch:**

   ```bash
   git checkout [your-branch-name]
   ```

3. **Start an interactive rebase:**

   ```bash
   git rebase -i upstream/rc/v12.0.0
   ```

4. **In the editor that opens, identify the commits that aren't yours.** These are likely the ones at the top of the list. 

5. **Change the word `pick` to `drop` for each commit you want to remove.** 

6. **Save and close the editor.**

8. **Force push your changes to your branch:** Note that force pushing is a dangerous operation because it overwrites commit history, so if you dropped the wrong commits you could lose work.

   ```bash
   git push -f origin [your-branch-name]
   ```

Once you've done this, the PR should be on the correct branch.

Let me know if you have any questions or run into any issues!

2024-07-27 07:15 UTC, dakshkanaujia commented
@BeksOmega , done with rebasing, please review!

2024-07-27 07:34 UTC, dakshkanaujia commented
If this is still incorrect , i have raised a new PR , on the `rc/v12.0.0` branch
[https://github.com/google/blockly/pull/8433](New_PR_LINK)

2024-07-30 02:10 UTC, closed without merging