fix: added 'blocklyHighlighted' CSS class to highlighted block's root…
google/blockly pull request #8407
Opened 2024-07-21 09:00 UTC by Shreshthaaa

# Details :
Added `blocklyHighlighted` CSS class to highlighted block's root svg.

# Fixes:

#8263

2024-07-30 02:14 UTC, BeksOmega requested changes
Thanks for your work! Just one fix.

2024-07-30 02:14 UTC, BeksOmega commented on core/renderers/common/path_object.ts
> +  }
Could you remove these and call the existing `setClass` method instead?

2024-08-02 19:43 UTC, BeksOmega commented
Heya @Shreshthaaa Are you still interested in working on this? (and your other open PRs?)

2024-08-02 19:48 UTC, Shreshthaaa commented
> Heya @Shreshthaaa Are you still interested in working on this? (and your other open PRs?)

Hi @BeksOmega , thank you for following up. I apologize for the delay. I've been quite busy lately but I am still interested in working on this and my other open PRs. I will address the requested changes in a day or two.

2024-08-04 20:04 UTC, Shreshthaaa commented
@BeksOmega  Hey, I have done the said changes. Kindly review.

2024-08-05 21:43 UTC, BeksOmega requested changes
Just pulled this down locally to test and I don't think this is working for the `renders/geras/path_object`. Can you refactor that to properly call `super`?

2024-08-06 13:52 UTC, Shreshthaaa commented
> Just pulled this down locally to test and I don't think this is working for the `renders/geras/path_object`. Can you refactor that to properly call `super`?

Hey, I made changes in `renderers/geras/path_object` itself. Kindly review.

2024-08-06 15:26 UTC, BeksOmega requested changes
Thanks for the changes but that doesn't quite do what I asked! In the geras path object it should call `super` to add the new CSS class. The only new code in the gears path object should be setting the `svgPathLight.style.display` values.

2024-08-07 10:37 UTC, Shreshthaaa commented
> Thanks for the changes but that doesn't quite do what I asked! In the geras path object it should call `super` to add the new CSS class. The only new code in the gears path object should be setting the `svgPathLight.style.display` values.

Hey, I have called `super` in the geras path object file to call the parent class method. Kindly check if the code looks correct now.

2024-08-12 16:47 UTC, BeksOmega commented
Heya @Shreshthaaa are you still interested in working on this?

2024-08-14 12:13 UTC, Shreshthaaa commented
> Heya @Shreshthaaa are you still interested in working on this?

Hey @BeksOmega, please review the update. Hopefully, everything is in line now. Thank you!

2024-08-14 16:06 UTC, merged