fix: removed the whole Drag category from the blocks
google/blockly pull request #8478
Opened 2024-08-11 15:33 UTC by abhinavjha0239

## The basics

- [x ] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)

## The details
### Resolves

 https://github.com/google/blockly/issues/8466
Fixes 

### Proposed Changes

    Removed the ‘Drag’ category from the blocks tested by toolbox_drag_test.mjs.
This change ensures that the test only includes blocks that add exactly one block to the workspace upon being dragged, aligning with the test’s original intent.

### Reason for Changes

### Test Coverage

### Documentation

### Additional Information

2024-08-12 17:30 UTC, BeksOmega approved these changes
One docs fix then should be good to go! Thanks for your work on this!

2024-08-12 17:30 UTC, BeksOmega commented on tests/browser/test/toolbox_drag_test.mjs
> +  // 'Drag',
```suggestion
  // Disabled due to #8466
  // 'Drag',
```

2024-08-13 10:47 UTC, abhinavjha0239 commented
@BeksOmega do I need to do anything else?

2024-08-13 15:37 UTC, BeksOmega commented
> @BeksOmega do I need to do anything else?

Yes! Please commit the change I suggested above =)

2024-08-14 09:08 UTC, abhinavjha0239 commented
@BeksOmega please review it.

2024-08-14 15:51 UTC, BeksOmega requested changes
Hello, we put comments above the thing being commented about so that it's clear what the comment refers to. Could you move the comment about disabling the drag category above the `// 'Drag',` line?

2024-08-14 16:17 UTC, abhinavjha0239 commented
@BeksOmega done please check it

2024-08-14 16:43 UTC, BeksOmega approved these changes
Sweet looks good to me! Once this passes CI I'll get it merged.

2024-08-14 16:44 UTC, BeksOmega commented
Looks like formatting is failing. Could you run `npm run format` and commit the changes?

2024-08-14 17:19 UTC, abhinavjha0239 commented
@BeksOmega done please look into it
Thank You

2024-08-14 18:17 UTC, BeksOmega commented
Looks great, thank you for your work on this!

2024-08-14 18:17 UTC, merged